detectors:
  IrresponsibleModule:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  FeatureEnvy:
    enabled: false

  UtilityFunction:
    public_methods_only: true

exclude_paths:
  - 'bin/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'log/**/*'
  - 'tmp/**/*'
  - 'app/assets/**/*'